export const Posts = [
  {
    id: "1",
    webSite: "https://market-jo-v1.herokuapp.com/",
    youtubeVid: "https://www.youtube.com/embed/iQe5ixN7JkA",
    img: "/images/market.png",
    title: "Talabat Alternative! , A full store-order experience !",
    description:
      "A comprehensive site for ordering products, especially food on the Internet, it allows the admin to add, remove and modify products and items from the control panel, receive orders in real time, close the store (stop receiving orders) and set the opening date, and much more!",
    tags: [
      "ReactJS",
      "JavaScript",
      "NodeJS",
      "Express",
      "REST API",
      "Tailwind",
      "Firebase",
      "Recoil",
    ],
    notes: [
      "The app is still in development, and there are a few things I want to add before turning it into a product for sale",
    ],
  },
  {
    id: "2",
    webSite: "https://free4english.com",
    youtubeVid: "https://www.youtube.com/embed/ei28yAXxPFk",
    img: "/images/free4english.png",
    title: "free4english, 3600 essential English words",
    description:
      "a web app that helps people to study the most common English words in a modren way for free",
    tags: [
      "ReactJS",
      "NextJS",
      "JavaScript",
      "NodeJS",
      "Express",
      "REST API",
      "Tailwind",
    ],
    notes: [],
  },
  {
    id: "3",
    webSite: "https://lang-speakup.herokuapp.com/",
    youtubeVid: "https://www.youtube.com/embed/Hhb2CQ9i-Vc",
    img: "/images/speakup.png",
    title: "SpeakUp , Voice-Chat App , language exchange and practice",
    description:
      "Fully functional voice and chat app, create custom groups, add and remove friends, see friends in online groups, and more great features.",
    tags: [
      "ReactJS",
      "JavaScript",
      "NodeJS",
      "Express",
      "REST API",
      "Mongodb",
      "socket.io",
      "webRTC",
      "JWT",
      "styled-components",
      "Auth",
      "Recoil",
      "Ant Design",
    ],
    notes: [
      "Created using React JS",
      "Ability to add and remove friends",
      "Auth with every request",
      "MongoDB as a data base",
      "Recoil for State Management",
      "Native WebRTC API",
    ],
  },
  {
    id: "4",
    webSite: "https://yt-clone-ecru.vercel.app/",
    youtubeVid: "https://www.youtube.com/embed/MMsx4loOZ6U",
    img: "/images/yt-clone.png",
    title: "youtube clone using next.js for front and backend",
    description:
      "A complete YouTube experience from SignUp to uploading videos to subscribing to channels to liking videos to Commenting to Searching to Some other cool features",
    tags: [
      "ReactJS",
      "NextJS",
      "JavaScript",
      "NodeJS",
      "REST API",
      "Tailwind",
      "Firebase",
      "Redux",
      "JWT",
      "Mongodb",
    ],
    notes: [
      "Created using Next JS",
      "Encrypt password after SigningUp",
      "Cookies for authorization",
      "MongoDB as a data base",
      "Firebase for Auth and Storage",
      "Redux for State Management",
    ],
  },
]

export const Categories = [
  "ReactJS",
  "NextJS",
  "JavaScript",
  "NodeJS",
  "Express",
  "GraphQL",
  "REST API",
  "Mongodb",
  "socket.io",
  "webRTC",
  "JWT",
  "Tailwind",
  "TypeScript",
  "Firebase",
  "Redux",
  "styled-components",
  "Auth",
  "React-Native",
  "Recoil",
  "React Query",
]

export const about = [
  "I am a software developer.",
  "Im 26, I live In Jordan / Madaba .",
  "I been freelancing since Three Years , React Since 2 Years.",
  "I have made quite a number of Apps for clients all over the world.",
  "",
  "if you didn't find me online i would be probably playing football ⚽.",
  // "I Really love Tea, Tea is my real cup of tea, you know .. 🍵.",
]
